Numpy Lesson on CodeAcademy.

In [51]:
import numpy as np


In [52]:
water_height = np.array([4.01, 4.03, 4.27, 4.29, 4.19, 4.15, 4.16, 4.23, 4.29, 4.19, 4.00, 4.22, 4.25, 4.19,
                         4.10,4.14, 4.03, 4.23, 4.08, 14.20,14.03, 11.20, 8.19, 6.18, 4.04,4.08, 4.11, 4.23,
                         3.99, 4.23])

In [53]:
mean_water_height = np.mean(water_height)
print'The mean water height is',mean_water_height, 'inches.'



The mean water height is 5.251 inches.


In [54]:
## If you wanted to sort, you could use the np.sort command.
np.sort(water_height)

array([ 3.99,  4.  ,  4.01,  4.03,  4.03,  4.04,  4.08,  4.08,  4.1 ,
        4.11,  4.14,  4.15,  4.16,  4.19,  4.19,  4.19,  4.22,  4.23,
        4.23,  4.23,  4.23,  4.25,  4.27,  4.29,  4.29,  6.18,  8.19,
       11.2 , 14.03, 14.2 ])

In [55]:
median_water_height = np.median(water_height)
print'The median water height is',median_water_height, 'inches.'

The median water height is 4.19 inches.


In [56]:
percentile_75_water_height = np.percentile(water_height, 75)
print'The 75th percentile for water height is',percentile_75_water_height, 'inches.'

The 75th percentile for water height is 4.265 inches.


In [57]:
std_water_height = np.std(water_height)
print'The standard deviation for water height is',std_water_height, 'inches.'

The standard deviation for water height is 2.784585367099861 inches.


In [58]:
## You can use the mean function to calculate the % of values in an array that meet some criteria.  For example, 
## the percent of values where the water height is greater than or equal to 8.0 and less than 8 would be:
np.mean(water_height >=8.0), np.mean(water_height <8.0)


(0.13333333333333333, 0.8666666666666667)

In [59]:
## Calculating the Mean of 2D Arrays
## If we have a two-dimensional array, np.mean can calculate the means of the larger array as well as the interior values.

## Let's imagine a game of ring toss at a carnival. In this game, you have three different chances to get all three rings onto a stick. 
## In our ring_toss array, each interior array (the arrays within the larger array) is one try, and each number is one
## ring toss. 1 represents a successful toss, 0 represents a fail.

##First, we can use np.mean to find the mean across all the arrays, which is the # of successful ring tosses overall.

ring_toss = np.array([[1, 0, 0, 0, 0], 
                          [1, 0, 1, 0 ,0], 
                          [1, 1, 1, 1, 1]])
np.mean(ring_toss)


0.5333333333333333

In [60]:
## To find the means of each interior array, we specify axis 1 (the "rows"):

np.mean(ring_toss, axis=1)


array([0.2, 0.4, 1. ])

In [63]:
##To find the means of each index position (i.e, mean of all 1st tosses, mean of all 2nd tosses, ...), we specifiy axis 0 (the "columns"):

np.mean(ring_toss, axis=0)

array([1.        , 0.33333333, 0.66666667, 0.33333333, 0.33333333])

Ended on Day 6 of Unit 3, Statistical distributions with Numpy